
defaultNote:
  title: 'The default note'
  text: 'This is the default note for the demo application'

assets:
  overrides:
    /: ../frontend/

server:
  rootPath: '/api/*'

database:
  driverClass: org.h2.Driver
  user: sa
  password: sa
  url: jdbc:h2:~/test
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute